dist: xenial
language: python
python:
- 3.7
- 3.8

env:
  global:
    secure: l7gCIgABmaej9Vf1VBCMVGLppiQl0gxZ/8o3XFnwPYilo0kK5khlOgYOpVrLxZWDOKlRv+n+VdJDG4zjPUD3Dr5k3Cu4QCMPCoJRoHE375ucalsHU80akIfBTOQl+udWeZ7alzSkFoQ4bvQ66VIDEvGnnFf4bbUuLTc49TTQAeyET3V1/FtT4uh/hQkSolCVZ2o1trQ879FkE7C7eHLhAoPeMqKoondqp9HBU+Wb6fSLMY6WXIN/EYeqTHimwprlVNJbOHJOpuTDqpIauemkJrASge0HM+K6LyAXUEKhBzwfGjnS+WUw2snGt8v8W6GT+uoAhQt3d0H1MQ8Uybh/yX053ZTa4RlL1uKNgd6EYKXrDh3ruA/MAEEKr0wr6x1VMb2AmkGzEVTMRlXp4RhXY0LvSoBiKKj6/Pj/VRygfwn9RxH1jKF7vK5Y/l4m+7/jFlUJpUiSL4GQ2VboQvhuodxkyCOI9X8SjaEhDiek6QzgaL080fkaqBZZrVbYU3f2SMUtxCvpQbwV7402lVpLEFNgpZuQApKKMVJYHbaKCUpaTOvwQMrzng94mTv1AAlgMepHc0tSkNBP2nANXRXbHtl0lbGiNlKSxMz/5TEMIk3W4NvyjiyMkfYkBjPhffd5al1wLQNYhNbg5iKUeQ6AEi9YuZkCq8j8+TieSWR88B8=

before_install:
- pip install --upgrade pip
- pip install poetry

install:
- poetry install
- sudo apt-get install libnotify-bin

script: make test

deploy:
- provider: script
  script: poetry publish --username rbpatt2019 --password $PYPI_PASS --build
  on:
    tags: true
    repo: rbpatt2019/ToDonePy
    python: 3.8

after_success:
- codecov
